name: edustar
description: A online education platform where students/developers can learn from it.
author: Vinoth Vino
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"

dependencies:
  flutter:
    sdk: flutter

  # My Custom Packages
  custom_buttons:
    path: packages/custom_buttons
  alert_dialogs:
    path: packages/alert_dialogs
  flutter_localizations:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.2
  flutter_rating_bar: ^3.0.1+1
  url_launcher: ^5.4.10
  flutter_swiper: ^1.1.6
  image_picker: ^0.6.7+1
  flutter_credit_card: ^0.1.3
  video_player: ^0.10.11+2
  webview_flutter: ^0.3.22+1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  apple_sign_in: ^0.1.0
  shared_preferences: ^0.5.7
  json_annotation: ^3.0.1
  provider: ^4.1.1
  path_provider: ^1.6.7
  share: ^0.6.4+3
  path: ^1.6.4
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  connectivity: ^0.4.8+5
  cached_network_image: ^2.2.0+1
  shimmer: ^1.1.1
  hive: 1.4.1+1
  hive_flutter: ^0.3.0+2
  get_it: ^4.0.2
  device_preview: ^0.4.5
  stripe_payment: ^1.0.7
  razorpay_flutter: ^1.2.2
  flutter_staggered_grid_view: "^0.2.7"
  credit_card_field: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  hive_generator: ^0.5.1
  json_serializable: ^3.3.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/images/
   - assets/images/courses/
   - assets/images/empty/
   - assets/images/onboard/
   - assets/lang/en.json
   - assets/lang/ta.json
   - assets/lang/ar.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
