class ViewRoutes {
  ViewRoutes._();

  static const String initial = '/';
  static const String splash = '/splash';
  static const String main = '/main';
  static const String home = '/home';
  static const String settings = '/settings';
  static const String login = '/login';
  static const String register = '/register';
  static const String otp = '/otp';
  static const String forgotPassword = '/forgotPassword';
  static const String resetPassword = '/resetPassword';
  static const String profileEdit = '/profileEdit';
  static const String searchCourse = '/searchCourse';
  static const String courseDetail = '/courseDetail';
  static const String purchaseCourseDetail = '/purchaseCourseDetail';
  static const String cart = '/cart';
  static const String review = '/review';
  static const String questionAnswer = '/questionAnswer';
  static const String questionAnswerDetail = '/questionAnswerDetail';
  static const String chooseLanguage = '/chooseLanguage';
  static const String chooseDisplayMode = '/chooseDisplayMode';
  static const String courseEnrolledStarted = '/courseEnrolledStarted';
  static const String categoryCourseList = '/categoryCourseListScreen';
  static const String instructorProfile = '/instructorProfileScreen';
  static const String instructorBioDetailedProfile = '/instructorBioDetaliedProfileScreen';
  static const String inviteFriends = '/inviteFriendsScreen';
  static const String privacyAboutTerms = '/privacyAboutTerms';
  static const String help = '/helpScreen';
  static const String aboutCourse = '/aboutCourseScreen';
  static const String courseResources = '/courseResourceScreen';
  static const String lectureResources = '/lectureResourceScreen';
  static const String announcements = '/announcementsScreen';
  static const String categoryList = '/categoryListScreen';
  static const String categoryDetail = '/categoryDetailScreen';
  static const String paymentSelection = '/PaymentSelectionScreen';
  static const String paymentExistingCard = '/paymentExistingCardScreen';
  static const String descriptionDetail = '/descriptionDetailScreen';
}
